BLSQ/openhexa-sdk-python

openhexa/sdk/pipelines/run.py
The distinction between path and name is not useful for the developer right now
=> fix: print something understandable when using add_file_output locally

openhexa/sdk/pipelines/parameter.py, tests/test_parameter.py
The parameter's "code" must be a valid python argument name
=> fix(Parameter): Validate parameter's code

docker/bootstrap.py, openhexa/cli/api.py
Pipelines folder can contain a `requirements.txt` file. This file is uploaded with the code and when present in the pod, will be installed using `pip install` in bootstrap.py.
This can help user install python-only libraries in case they need a special package for their use case.
=> feat(dependencies): Install extra dependencies if provided in pipeline

openhexa/cli/cli.py
Fix a bug where it's possible to add a workspace with an invalid token (the workspace is unusable)
=> fix(CLI): Do not add a workspace that cannot be found online

openhexa/sdk/pipelines/parameter.py
This PR simply updates the type annotations so that floats are officially accepted in the @parameter decorator.
=> fix: Adapt type parameter typing to accept floats in @parameter

openhexa/cli/cli.py
Users can run the pipeline without passing a configuration
`openhexa pipelines run .`
=> fix(CLI): Do not require a config even if it's empty

.github/workflows/release-please.yml, openhexa/__init__.py, openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/sdk/__init__.py, setup.cfg, setup.py
The goal of this PR is to make the packaging setup compliant with namespace packages guidelines (see https://packaging.python.org/en/latest/guides/packaging-namespace-packages/ and https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-namespace-packages).
Accordingly :
=> fix: use proper namespace package setup

openhexa/cli/cli.py
Currently, this message often appears as "Pipeline found in . does not exist", which is confusing
=> Simplify messages displayed in CLI for new pipelines

openhexa/cli/api.py, tests/test_api.py
Relative to [issue](https://github.com/BLSQ/openhexa-team/issues/496) : we now filter and prevent upload of workspace/ folder contents.
=> fix(Pipelines): prevent upload of workspace folder content

openhexa/sdk/pipelines/parameter.py, openhexa/sdk/pipelines/pipeline.py
This PR adds docstrings for the `@pipeline` and `@parameter` decorators, following the Numpy styleguide.
=> doc: Add docstrings for @pipeline and @parameter

openhexa/sdk/workspaces/connection.py, openhexa/sdk/workspaces/workspace.py, tests/test_workspace.py
Relative to [issue](https://github.com/BLSQ/openhexa-team/issues/512) : hide sensitive informations when printing  connection
=> refacto(Connections): hide sensitive informations when printing  connection

openhexa/sdk/pipelines/utils.py, openhexa/sdk/workspaces/workspace.py, tests/test_workspace.py
Same as `workspace.files_path` but for `/home/hexa/tmp/`.
=> feat: Add tmp_path property on workspace

.github/workflows/ci.yml, pyproject.toml
This PR:
- Adds support for Python 3.11
- Linked: updates `multiprocess` to latest version which supports Python 3.11
- Adds a Python version matrix to the test workflow
=> feat: Add support for Python 3.11

openhexa/sdk/pipelines/parameter.py, openhexa/sdk/pipelines/pipeline.py, openhexa/sdk/pipelines/utils.py, tests/test_parameter.py, tests/test_pipeline.py
Enhance the parameter decorator by adding more supported types
=> feat : add parameter of type connection (IASO,GCS..)

openhexa/cli/cli.py, openhexa/sdk/pipelines/utils.py
Allow users to specifiy workspace docker image (name & tag)  in workspace.yaml when running pipeline in local with `openhexa pipelines run`.
=> feat(Workspaces): allow user to specify workspace docker image

openhexa/cli/cli.py
Users were complaining the image was not the latest one. The default behavior should be to always download the latest image instead
=> fix(Docker): Always force pull the image

openhexa/sdk/__init__.py, openhexa/sdk/pipelines/parameter.py, tests/test_parameter.py
Add support for dataset parameter type in sdk. As we have done for the connection, user can now define parameter of type dataset via @parameter("dataset_identifier",....). The corresponding dataset instance will be automatically injected and available to use.
=> feat(Parameter): add support for Dataset parameter type

openhexa/cli/api.py, openhexa/cli/cli.py, tests/test_api.py
When deleting a pipeline we now throw an error if the pipeline is in Running or Queued state and show a message to prevent the user.
=> feat(CLI): check if permission_denied is thrown

openhexa/cli/api.py, openhexa/sdk/pipelines/runtime.py, tests/test_ast.py
In the former way of extracting the metadata of the pipeline, it was possible to do computations in the args. Since we now use the AST, it has to be a specific type (per arg)
=> fix(CLI): Check if args of decorators are of a primitive type

pyproject.toml
The problem is encountered on our users' computer. As we do not use the latest features of urllib and the package still receives security updates, it's safe to pin a older version for now.
=> fix(urllib): Use urllib < 2 to avoid problemw with openssl being not uptodate

README.md, openhexa/cli/api.py, openhexa/sdk/pipelines/pipeline.py, openhexa/sdk/pipelines/utils.py, openhexa/sdk/workspaces/current_workspace.py
When we work locally we provide path "/home/hexa/pipeline" to search for configuration and file_path, which is incorrect.
=> fix: copy workspace folder to correct path

openhexa/sdk/workspaces/current_workspace.py, tests/test_workspace.py
The SDK encounters an error when attempting to establish a connection from a workspace.yml file if there are multiple connections defined with the same prefix.
See [issue](https://bluesquare.atlassian.net/jira/software/c/projects/HEXA/boards/330?assignee=712020%3A1d0055ff-af59-47b7-b48d-4d37e2a0d0b9&selectedIssue=HEXA-1038)
=> fix(Connections): fix shallow matching when retrieving connection fields

openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/sdk/pipelines/parameter.py, openhexa/sdk/pipelines/pipeline.py, openhexa/sdk/pipelines/runtime.py, openhexa/utils/stringcase.py, tests/test_ast.py, tests/test_parameter.py
Allows choices to contain list as parameter
Checks if all items in list of default items are in choices
=> fix: fixes the default value to be of type list

.github/pull_request_template.md, .gitignore, openhexa/cli/settings.py, tests/test_cli.py
When pushing a pipeline using the SDK, I was getting `http://localhost:8000//workspaces/test/pipelines/simple-etl` which contains an extra slash.  This PR fixes the issue, adds a unit test to cover the change and some parts of `pipelines_push` method.
- Strip the slash in the url method
- Reuse the api_url method to compute the public api url
- Add a unit test to cover the push method
- Refactor the unit tests to avoid duplication of code and constants
- Add the Pr template from other repos
- Pushing a pipeline works with and without slash at the end of the config url
- Unit test are still passing
=> fix: Remove slash from api_url

openhexa/cli/api.py
Meaningful error message related to https://github.com/BLSQ/openhexa-app/pull/849
- Meaningful error message & add error enum
- Trying to push a pipeline with a duplicate name fails gracefully
=> fix: Prevent saving pipeline versions with the same name

openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/sdk/pipelines/runtime.py, tests/test_cli.py
PR related to https://github.com/BLSQ/openhexa-app/pull/857
Pipeline versions should auto-increment, a name for the version should be optional
- Make the name otpional
- Get and show the pipeline version number
- Pushing a pipeline can be done with and without version name
=> feat!: Set a default version number for each pipeline version, make version name optional

examples/pipelines/logistic_stats/pipeline.py, openhexa/cli/api.py, openhexa/sdk/pipelines/log_level.py, openhexa/sdk/pipelines/parameter.py, openhexa/sdk/pipelines/pipeline.py, openhexa/sdk/pipelines/runtime.py, tests/test_ast.py, tests/test_parameter.py, tests/test_pipeline.py, tests/test_workspace.py
adds `widget` field  to parameters
adds `connection` field to parameters
adds check on connection between parameters
removes remainings of parameter specs 
https://bluesquare.atlassian.net/browse/HEXA-1134
=> feat(Parameter): HEXA-1134 adds dhis2 parameters widget and connection fields plus validation

openhexa/cli/api.py, openhexa/cli/cli.py, tests/test_cli.py
Ask if a template version needs to be created when pushing a new pipeline version
- Import graphQL query to create the template version
- `propose_to_create_template_version` helper to automate the template version creation
- Extended existing unit test to verify that the template version creation is happening
When pushing a new pipeline version it should be possible to create a template version as well
=> feat: Support template version creation on push (HEXA-1182)

openhexa/cli/cli.py
It feels like there was an error when the user sees 'Aborted'
=> fix(Templates): Do not abort when the user do not want to create a template version

openhexa/cli/cli.py, tests/test_cli.py
The CLI is used by Github actions to automatically push pipelines. We needed to provide a way to specify the code of the pipeline that will be updated in a non interactive way
- Add the option
- Check that the not non interactive mode has a code
- Get the pipeline from the code and ensure it exists
- Unit tests to cover all cases
=> feat: cli users should have a way to give a pipeline code in the command to upload a pipeline (HEXA-1216)

openhexa/cli/api.py, openhexa/cli/cli.py, tests/test_cli.py
The permission type of create template version has been changed from boolean to more complex structure with reasons for permission denial.
- Fix the parsing of the permission
=> fix: getting permissions of create template version (HEXA-1228)

openhexa/sdk/pipelines/parameter.py
When decorating a pipeline with `@parameter`, we use the `type=` argument to specify parameter type:
``` python
@pipeline(...)
@parameter(
code="src_dhis2",
type=DHIS2Connection,
name="Source DHIS2 instance",
)
@parameter(
code="dst_dataset",
type=Dataset,
name="Output dataset",
)
@parameter(
code="org_units",
type=str,
multiple=True,
name="Organisation units",
)
def my_pipeline():
...
```
We are not passing an instance of a class but the class/type itself. Therefore the annotated type of `type` should be of type `type` and not `str | DHIS2Connection | Dataset | ...`.
=> fix: type of arg `type` should be of type `type`

openhexa/sdk/workspaces/current_workspace.py
Remove the static link between CLI and SDK
checked with : `conda build . --channel conda-forge --channel bioconda`
=> fix: circular dependency

openhexa/sdk/pipelines/utils.py
Add a way to pass env variables to containers through `workspace.yaml`.
Parse `env` section in `workspace.yaml` and add the env variables to the local workspace config.
Might be better to pass env variables through an argument of `openhexa pipelines run` instead? Or fetch these values automatically in the SDK instead of requiring the user to write down these env variables?
This allows to do things such as:
* Using connections from remote workspace in local runs
* Reading & writing datasets from remote workspace in local runs
* Reading & writing to workspace database in local runs
* Potentially also do all that in CI/CD pipelines to test pipelines before deployment
`workspace.yaml`:
Reading and writing remote datasets:
=> feat: pass env variables to container

openhexa/cli/api.py
The file was moved, but the path not modified
=> fix: path to schema

README.md, openhexa/cli/api.py, openhexa/graphql/graphql_client/__init__.py, openhexa/graphql/graphql_client/client.py, openhexa/graphql/graphql_client/enums.py, openhexa/graphql/graphql_client/input_types.py, openhexa/graphql/queries.graphql, openhexa/graphql/schema.generated.graphql
- The GraphQL is too recent for demo/prod, it's safer to set it to the schema in v1.11.0
- Regenerate types using ariadne-codegen
- Handle exception gracefully
=> fix: Set schema to Prod/Demo schema, handle exception gracefully

openhexa/sdk/__init__.py, openhexa/sdk/pipelines/__init__.py, openhexa/sdk/pipelines/current_pipeline.py, openhexa/sdk/pipelines/run.py
implements:
- `current_run.id` property to pin to the run_id inside pipeline context
implements:
- `current_pipeline` object to display pipeline parameters
fixes runtime import OpenHexa and instantiation
=> Hexa 1330 current run and pipeline

.github/workflows/ci.yml
We have two jobs in parallel :
- ci for every branch commit
- publish on release 
When we publish we do conda build and it fails when we forget to add packages, but as the build status is only displayed from CI flow, we never get notified until docker-images build fails. 
I have added packages build to CI flow so we notified in CI if there is an unmet dependency
Closes: https://bluesquare.atlassian.net/browse/HEXA-1331?atlOrigin=eyJpIjoiYWU4Y2ZiYjI1ZWRlNGQ3Njk0ZDEyMzgzMzAwNjc1YjUiLCJwIjoiaiJ9
=> fix: add conda build to ci workflow

openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/cli/settings.py, openhexa/graphql/base_openhexa_client.py, openhexa/sdk/utils.py, openhexa/utils/session.py, tests/conftest.py, tests/test_cli.py, tests/test_ssl_errors.py
Closes https://bluesquare.atlassian.net/browse/HEXA-1350
- Adds HEXA_VERIFY_SSL env variable, if disabled (0, false) api requests to OH instance will skip TLS verification
- Disables warnings in case when HEXA_VERIFY_SSL is disabled
- Provide suggestion to disable SSL verification in if SSL verification have failed
how to test:
```bash
cd openhexa-sdk-python
source venv/bin/activate
pip install .
openhexa config set_url=TLS_ENABLED_URL
export HEXA_VERIFY_SSL=true/false
openhexa workspaces add "workspace"
openhexa pipelines list
```
=> feat: add HEXA_VERIFY_SSL option to disable ssl certificate
