openhexa/sdk/pipelines/utils.py, openhexa/sdk/workspaces/connection.py, openhexa/sdk/workspaces/workspace.py, tests/test_workspace.py
Add S3, gcs and custom connection support (local and workspace)
=> Add S3, gcs and custom connection support (local and workspace)

README.md, openhexa/sdk/pipelines/pipeline.py, openhexa/sdk/pipelines/run.py, openhexa/sdk/utils.py, openhexa/sdk/workspaces/workspace.py, tests/test_environment.py
Environments: 
- Jupyter
- Local
- Pipeline runner
=> feat(Environment): Add a Environment env variable to be able to differientate the different running environments

openhexa/cli/api.py
If we find a "python" file, we consider it as part of a virtual environment and we exclude files from this folder
=> fix(CLI): Exclude venv/.venv from the zip file

openhexa/sdk/pipelines/run.py
Relative to  [issue](https://github.com/BLSQ/openhexa-team/issues/396).
Changes :
- Convert log message to string before notifying hexa_server.
=> fix(Logs): convert log message to str

openhexa/sdk/pipelines/parameter.py
=> feat(Parameter): add float to supported types

docker/bootstrap.py
This is linked to https://github.com/BLSQ/openhexa-app/pull/488
=> feat(Credentials): Use the new endpoint to get the env vars from the backend

openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/cli/utils.py
Prevent user to push of a new version with parameters for scheduled pipelines.
=> feat(Pipelines): prevent push of version  with params for scheduled pipeline.

openhexa/sdk/pipelines/utils.py, openhexa/sdk/workspaces/workspace.py, tests/test_workspace.py
- Deprecate 'slug' in favor of 'identifier' when getting connections for a workspace
- Fix a problem with the generation of env variables in local
=> Fix connections bug and slug

openhexa/cli/api.py, openhexa/cli/cli.py
Set timeout value when uploading a new version
=> fix(Pipelines): set timeout value when uploading a version

openhexa/sdk/pipelines/pipeline.py
Change _name_ by _code_ in error message.
=> style(Pipelines): fix typo on pipeline code error.

openhexa/sdk/pipelines/utils.py, openhexa/sdk/workspaces/connection.py, openhexa/sdk/workspaces/workspace.py, tests/test_workspace.py
Add support for IASO connection.
=> feat(Connections): add support for IASO connection

openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/sdk/pipelines/utils.py, pyproject.toml, tests/test_cli.py
And add a few tests for the CLI.
The question is only asked when user tries to push his pipeline or when he tries to run it.
=> fix(CLI): Ask the user to create the workspace.yaml if not found

openhexa/sdk/utils.py, openhexa/sdk/workspaces/workspace.py, pyproject.toml, tests/test_dataset.py
Users can create datasets with:
```python
workspace.create_dataset("My dataset", "Description")
```
=> Create dataset with the SDK

openhexa/sdk/workspaces/workspace.py
=> feat(Workspaces): list datasets in a workspace

openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/cli/settings.py, tests/conftest.py, tests/fixtures/test_pipeline/.gitignore, tests/fixtures/test_pipeline/data/dummy.txt, tests/fixtures/test_pipeline/pipeline.py, tests/test_api.py, tests/test_cli.py
It helps to use token & current workspace from env vars if needed.
=> Use a new way to load settings

openhexa/cli/api.py, openhexa/cli/cli.py, openhexa/cli/settings.py, openhexa/sdk/pipelines/pipeline.py, pyproject.toml, tests/test_cli.py
- Check that docker exists
- Use docker python package instead of popen
- Configure logging
- Use same date formatting for all the logs of the pipeline
=> Check that docker exists and is running

openhexa/sdk/pipelines/parameter.py, openhexa/sdk/pipelines/utils.py, openhexa/sdk/workspaces/__init__.py, openhexa/sdk/workspaces/connection.py, openhexa/sdk/workspaces/current_workspace.py, tests/test_parameter.py, tests/test_pipeline.py, tests/test_workspace.py
See [issue](https://bluesquare.atlassian.net/jira/software/c/projects/HEXA/boards/333?assignee=712020%3A1d0055ff-af59-47b7-b48d-4d37e2a0d0b9&selectedIssue=HEXA-962) : connections are now retrieved using graphql API.
=> feat(Workspaces): get connections from graphql API

openhexa/sdk/workspaces/current_workspace.py, tests/test_workspace.py
User lowercase identifier when getting connection from API.
=> fix(Connections): specify connection workspace

openhexa/cli/api.py, openhexa/sdk/utils.py, openhexa/utils/__init__.py, openhexa/utils/session.py
Add a retry mechanism for the communication with the API
=> feat: add a retry mechanism for API call

openhexa/sdk/datasets/dataset.py
See [issue](https://bluesquare.atlassian.net/browse/HEXA-1018?focusedCommentId=62975) .
=>  feat(DatasetFiles): add helper to check if file exists

examples/pipelines/logistic_stats/pipeline.py, openhexa/sdk/pipelines/runtime.py, tests/test_ast.py
And we help them by providing an explanation on what to do.
=> Users should not be able to push new versions of their pipelines with a code and a name

openhexa/cli/cli.py
Allow cancelling during pipeline selection for push (https://whimsical.com/testing-notes-march-2025-Dj7QepTsa731LwFwjTqSNH)
=> feat: Add possibility to abort during pipeline selection for push (HEXA-1209)

examples/pipelines/dhis2/.gitignore, examples/pipelines/dhis2/pipeline.py, openhexa/sdk/pipelines/parameter.py, openhexa/sdk/pipelines/runtime.py, tests/test_ast.py
+ an example of DHIS2 pipeline using widgets
=> Better Validation of the DHIS2 widgets

examples/pipelines/dhis2/pipeline.py, openhexa/sdk/pipelines/parameter.py
Fixes value set in dictionary to the  widget parameter field.
=> fix: dictionary lapping for widget

openhexa/sdk/pipelines/parameter.py
Fixes parameter decorator, connection field was missing.
=> fix: adds connection field to decorator

openhexa/sdk/__init__.py
updates exports with DHIS2Widget
=> fix(parameter): updates exports in sdk with widget

openhexa/sdk/datasets/dataset.py, openhexa/sdk/pipelines/pipeline.py, openhexa/sdk/pipelines/runtime.py, openhexa/sdk/utils.py
Make all calls to OH api optional with ssl
=> feat(client) : make ssl option for all calls to OH api

openhexa/cli/api.py, openhexa/sdk/utils.py, tests/test_ssl_errors.py
I have missed to add exception wrapper for api calls as done for cli
=> fix: wrapped  exceptions, making text more UI friendly 
